[package]
name = "bj"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
regex = "1.12.2"
reqwest = { version = "0.11", features = ["blocking"] } # 또는 async용 비동기 설정
scraper = "0.14"
unicodeit = "0.1"
